version: '3.7'

services:
    server:
        build:
            context: ./calculatorAPI
        ports: 
            ["5000:5000"]
    
    client:
        build:
            context: ./calculator-web
        ports:
            ["3000:3000"]
        